
version: '3.8'

services:
  product-service:
    build: ./product-service
    ports:
      - "3000:3000"
    volumes:
      - ./product-service/products.json:/app/products.json
    depends_on:
      - calculator-service

  calculator-service:
    build: ./calculator-service
    ports:
      - "5000:5000"
